apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: us.gcr.io/ticketing-dev-404114/ticketing-tickets # Same as skaffold.yaml file
          env:
            - name: MONGO_URI # Name of the environment variable which we can refer from inside of the service
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_SECRET # Name of the environment variable which we can refer from inside of the service
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # Name of the running secret service
                  key: jwt_key
            - name: NODE_ENV # Name of the environment variable which we can refer from inside of the service
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # Name of the running secret service
                  key: node_env

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000 # Port for the Service to run - will redirect the traffic to targetPort can be same as targetPort
      targetPort: 3000 # Actual Port that is listening to incoming traffic in the Pod
